# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-07 11:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'оферта',
                'verbose_name_plural': 'оферты',
            },
        ),
    ]
