# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
