# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_auto_20161122_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
