# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_oferta_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
