# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
