# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 07:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161011_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'статическая страница', 'verbose_name_plural': 'статические страницы'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_photo',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
    ]
