# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20161012_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефоны')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('worktime', models.CharField(max_length=200, verbose_name='Время работы')),
            ],
        ),
        migrations.CreateModel(
            name='Schelude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('time', models.IntegerField(choices=[(1, '09:00 - 10:00'), (2, '10:00 - 11:00'), (3, '11:00 - 12:00'), (4, '12:00 - 13:00'), (5, '13:00 - 14:00'), (6, '14:00 - 15:00'), (7, '15:00 - 16:00'), (8, '16:00 - 17:00'), (9, '17:00 - 18:00'), (10, '18:00 - 19:00'), (11, '19:00 - 20:00'), (12, '20:00 - 21:00')], verbose_name='Время')),
                ('content', models.CharField(max_length=200, verbose_name='Содержание')),
                ('company', models.IntegerField(choices=[(1, 'TOP-FITNESS'), (2, 'Studio')], verbose_name='Компания')),
            ],
        ),
    ]
