# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_club_schelude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schelude',
            options={'verbose_name': 'занятие', 'verbose_name_plural': 'расписание'},
        ),
        migrations.AlterUniqueTogether(
            name='schelude',
            unique_together=set([('day', 'time')]),
        ),
    ]
