# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20161014_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
    ]
