# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_club_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'клуб', 'verbose_name_plural': 'клубы'},
        ),
        migrations.AddField(
            model_name='schelude',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club'),
        ),
    ]
