# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20161014_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schelude',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='Клуб'),
        ),
        migrations.AlterUniqueTogether(
            name='schelude',
            unique_together=set([('day', 'time', 'club')]),
        ),
    ]
