# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20161014_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayclub',
            options={'verbose_name_plural': 'расписание'},
        ),
    ]
