# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20161014_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayclub',
            unique_together=set([('club', 'day')]),
        ),
    ]
