# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_staticpage_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='Клуб')),
            ],
        ),
    ]
