# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_gym'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayClub',
            new_name='WeekDay',
        ),
    ]
