# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20161017_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='club',
        ),
        migrations.AddField(
            model_name='weekday',
            name='gym',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gym', verbose_name='Клуб'),
        ),
    ]
