# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20161017_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'зал', 'verbose_name_plural': 'залы'},
        ),
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
    ]
