# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20161018_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='pagetype',
            field=models.CharField(choices=[('stock', 'Акции'), ('fitness', 'Система ТОП-Фитнесс'), ('about', 'О компании'), ('service', 'Услуги')], default='', max_length=10, verbose_name='Тип страницы'),
        ),
    ]
