# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_staticpage_pagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='slug',
        ),
    ]
