# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_staticpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='клуб'),
        ),
    ]
