# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_news_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='pagetype',
            field=models.CharField(choices=[('stock', 'Акции'), ('service', 'Услуги')], default='', max_length=10, verbose_name='Тип страницы'),
        ),
    ]
