# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20161118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='program',
            field=models.IntegerField(choices=[(1, 'TOP-FITNESS'), (2, 'Studio'), (3, 'Прочее')], verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.IntegerField(choices=[(1, '08:00 - 09:00'), (2, '09:00 - 10:00'), (3, '10:00 - 11:00'), (4, '11:00 - 12:00'), (5, '12:00 - 13:00'), (6, '13:00 - 14:00'), (7, '14:00 - 15:00'), (8, '15:00 - 16:00'), (9, '16:00 - 17:00'), (10, '17:00 - 18:00'), (11, '18:00 - 19:00'), (12, '19:00 - 20:00'), (13, '20:00 - 21:00')], verbose_name='Время'),
        ),
    ]
