# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20161118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='program',
            field=models.IntegerField(choices=[(1, 'TOP-FITNESS'), (2, 'Studio'), (3, '\u041f\u0440\u043e\u0447\u0435\u0435')], verbose_name='\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='pagetype',
            field=models.CharField(choices=[(b'stock', b'\xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'), (b'fitness', b'Top Fitness'), (b'service', b'\xd0\xa3\xd1\x81\xd0\xbb\xd1\x83\xd0\xb3\xd0\xb8')], default=b'', max_length=10, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
