# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20161118_1518'),
        ('mainapp', '0029_auto_20161118_1637'),
    ]

    operations = [
    ]
