# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20161124_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abon_price',
            field=models.IntegerField(default=0, verbose_name='Цена абонемента'),
        ),
    ]
