# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_club_abon_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField(choices=[(1, 'Бесплатный фитнес-день'), (2, 'Заказать звонок'), (3, 'Заказать абонемент')], verbose_name='Форма')),
                ('context', ckeditor.fields.RichTextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='Клуб')),
            ],
        ),
    ]
