# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club'),
        ),
    ]
