# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_slider_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Подзаголовок'),
        ),
    ]
