# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_forms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
    ]
