# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20161202_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='заголовок'),
        ),
    ]
