# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_slider_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_url',
            field=models.URLField(blank=True, verbose_name='Ссылка кнопки'),
        ),
    ]
