# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_form_title'),
        ('mainapp', '0036_slider_order'),
    ]

    operations = [
    ]
