# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20161208_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='abon_price',
        ),
        migrations.AddField(
            model_name='club',
            name='callibri',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Callibri'),
        ),
        migrations.AlterField(
            model_name='form',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
