# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20161208_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.IntegerField(choices=[(1, '\u0411\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u044b\u0439 \u0444\u0438\u0442\u043d\u0435\u0441-\u0434\u0435\u043d\u044c'), (2, '\u0417\u0430\u043a\u0430\u0437\u0430\u0442\u044c \u0437\u0432\u043e\u043d\u043e\u043a'), (3, '\u0417\u0430\u043a\u0430\u0437\u0430\u0442\u044c \u0430\u0431\u043e\u043d\u0435\u043c\u0435\u043d\u0442')], verbose_name='\u0424\u043e\u0440\u043c\u0430')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u043f\u0440\u043e\u0441\u0430')),
                ('daterequest', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0430 \u0441 \u0444\u043e\u0440\u043c',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u0441 \u0444\u043e\u0440\u043c',
            },
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='pagetype',
            field=models.CharField(choices=[(b'stock', b'\xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'), (b'fitness', b'Top Fitness'), (b'service', b'\xd0\xa3\xd1\x81\xd0\xbb\xd1\x83\xd0\xb3\xd0\xb8'), (b'trainers', b'\xd0\xa2\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb5\xd1\x80\xd1\x8b')], default=b'', max_length=10, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
