# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20161212_1421'),
        ('mainapp', '0031_auto_20161122_1758'),
    ]

    operations = [
    ]
