# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 12:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_merge_20161213_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('url', models.URLField(blank=True, default=b'')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='daterequest',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='pagetype',
            field=models.CharField(choices=[(b'stock', b'\xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'), (b'fitness', b'Top Fitness'), (b'service', b'\xd0\xa3\xd1\x81\xd0\xbb\xd1\x83\xd0\xb3\xd0\xb8'), (b'trainers', b'\xd0\xa2\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb5\xd1\x80\xd1\x8b')], default=b'', max_length=10, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
