# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 10:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20161213_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='\u0441\u043b\u0430\u0433'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, default=b'', verbose_name='URL'),
        ),
    ]
