# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20170207_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0433\u043e\u0440\u043e\u0434', 'verbose_name_plural': '\u0433\u043e\u0440\u043e\u0434\u0430'},
        ),
    ]
