# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20170207_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club'),
        ),
    ]
