# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20170208_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=b'', max_length=200, unique=True, verbose_name='\u0441\u043b\u0430\u0433'),
        ),
    ]
