# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 13:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u043a\u0440\u0430\u0442\u043a\u0438\u0439 \u0442\u0435\u043a\u0441\u0442')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u043f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431')),
            ],
            options={
                'verbose_name': '\u0430\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0430\u043a\u0446\u0438\u0438',
            },
        ),
    ]
