# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_stock_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u0434\u0430\u0442\u0430'),
        ),
    ]
