# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 13:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20170209_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(default=b'', max_length=200, unique=True, verbose_name='\u0441\u043b\u0430\u0433')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='\u0434\u0430\u0442\u0430')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430',
                'verbose_name_plural': '\u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='club',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
