# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='club',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club'),
        ),
    ]
