# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20170210_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='title',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
