# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_staticpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0434\u0430\u0442\u0430'),
        ),
    ]
