# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_auto_20170210_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnesZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u0440\u0438\u0441\u0443\u043d\u043e\u043a')),
                ('link', models.URLField(verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431')),
            ],
            options={
                'verbose_name': '\u0444\u0438\u0442\u043d\u0435\u0441-\u0437\u043e\u043d\u0430',
                'verbose_name_plural': '\u0444\u0438\u0442\u043d\u0435\u0441-\u0437\u043e\u043d\u044b',
            },
        ),
    ]
