# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_fitneszone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='show_button',
            field=models.BooleanField(default=False, verbose_name='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='stock',
            name='text_button',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='stock',
            name='url_button',
            field=models.URLField(default=b'//', verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
    ]
