# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_auto_20170216_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='text_button',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url_button',
            field=models.URLField(blank=True, default=b'//', null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
    ]
