# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_auto_20170216_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
