# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_auto_20170217_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'', verbose_name='\u043c\u0438\u043d\u0438\u0430\u0442\u044e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'', verbose_name='\u043c\u0438\u043d\u0438\u0430\u0442\u044e\u0440\u0430'),
        ),
    ]
