# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_auto_20170220_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='url_button',
            field=models.URLField(blank=True, default=b'', null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
    ]
