# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 08:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_auto_20170220_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor.fields.RichTextField(default=b'', max_length=210, verbose_name='\u043a\u0440\u0430\u0442\u043a\u0438\u0439 \u0442\u0435\u043a\u0441\u0442 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=65, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_text',
            field=ckeditor.fields.RichTextField(default=b'', max_length=210, verbose_name='\u043a\u0440\u0430\u0442\u043a\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=65, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
