# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_auto_20170221_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='short_text',
        ),
    ]
