# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 09:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_remove_stock_short_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431')),
            ],
            options={
                'verbose_name': '\u0442\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439 \u0431\u043b\u043e\u043a',
                'verbose_name_plural': '\u0442\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0435 \u0431\u043b\u043e\u043a\u0438',
            },
        ),
    ]
