# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_edittextfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='edittextfield',
            name='page',
            field=models.IntegerField(choices=[(1, b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbc\xd1\x8b'), (2, b'\xd0\xa0\xd0\xb0\xd1\x81\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')], default=1, verbose_name='\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='edittextfield',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431'),
        ),
        migrations.AlterUniqueTogether(
            name='edittextfield',
            unique_together=set([('club', 'page')]),
        ),
    ]
