# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20170222_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edittextfield',
            name='page',
            field=models.IntegerField(choices=[(1, b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbc\xd1\x8b')], default=1, verbose_name='\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
    ]
