# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_auto_20170222_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text="1. \u041d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 <a href='https://elfsight.com/youtube-channel-plugin-yottie/jquery/#demo'>\u0441\u0441\u044b\u043b\u043a\u0430</a> \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u0442\u0435 \u0432\u0438\u0434\u0436\u0435\u0442.<br>\n                      2. \u0412 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u043c \u043f\u0443\u043d\u043a\u0442\u0435 Get Code \u0441\u043a\u043e\u043f\u0438\u0440\u0443\u0439\u0442\u0435 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u044b\u0439 \u043a\u043e\u0434 \u0432\u0438\u0434\u0436\u0435\u0442\u0430 (2-\u043e\u0435 \u043f\u043e\u043b\u0435).<br>\n                      3. \u0412\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u044d\u0442\u043e\u0442 \u043a\u043e\u0434 \u0432 \u044d\u0442\u043e \u043f\u043e\u043b\u0435.")),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', unique=True, verbose_name='\u043a\u043b\u0443\u0431')),
            ],
            options={
                'verbose_name': 'YouTube \u043a\u0430\u043d\u0430\u043b',
                'verbose_name_plural': 'YouTube \u043a\u0430\u043d\u0430\u043b\u044b',
            },
        ),
    ]
