# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0070_youtubechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Club', verbose_name='\u043a\u043b\u0443\u0431'),
        ),
    ]
