# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_auto_20170411_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set([('form', 'club')]),
        ),
    ]
