# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0072_auto_20170413_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.IntegerField(choices=[(2, '\u0417\u0430\u043a\u0430\u0437\u0430\u0442\u044c \u0437\u0432\u043e\u043d\u043e\u043a'), (3, '\u0417\u0430\u043a\u0430\u0437\u0430\u0442\u044c \u0430\u0431\u043e\u043d\u0435\u043c\u0435\u043d\u0442')], verbose_name='\u0424\u043e\u0440\u043c\u0430'),
        ),
    ]
