# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0073_auto_20170414_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='program',
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.IntegerField(choices=[(1, '08:00 - 09:00'), (2, '09:00 - 10:00'), (3, '10:00 - 11:00'), (4, '11:00 - 12:00'), (5, '12:00 - 13:00'), (6, '13:00 - 14:00'), (7, '14:00 - 15:00'), (8, '15:00 - 16:00'), (9, '16:00 - 17:00'), (10, '17:00 - 18:00'), (11, '18:00 - 19:00'), (12, '19:00 - 20:00'), (13, '20:00 - 21:00'), (14, '21:00 - 22:00'), (15, '22:00 - 23:00')], verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
    ]
