# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_auto_20170424_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('order',), 'verbose_name': '\u0430\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u0430\u043a\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='stock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
