# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0006_auto_20170430_2215'),
        ('mainapp', '0077_auto_20170427_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_cash_register.CashRegister'),
        ),
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u043a\u043e\u0434 \u0432 \u0441\u0438\u0441\u0442\u0435\u043c\u0435 1\u0421'),
        ),
    ]
