# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0078_auto_20170515_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, help_text='\u0414\u043e\u043b\u0436\u0435\u043d \u0441\u043e\u0432\u043f\u0430\u0434\u0430\u0442\u044c \u0441 \u043a\u043e\u0434\u043e\u043c \u0438\u0437 API https://api.wge.ru/sportclub/hs/fitnes_mob/clubs', max_length=200, null=True, unique=True, verbose_name='\u043a\u043e\u0434 \u0432 \u0441\u0438\u0441\u0442\u0435\u043c\u0435 1\u0421'),
        ),
    ]
