# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_auto_20170516_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='context',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_url',
            field=models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
