# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_auto_20170516_1634'),
        ('mainapp', '0079_auto_20170517_1800'),
    ]

    operations = [
    ]
