# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0080_auto_20170619_1739'),
        ('mainapp', '0080_merge_20170518_2119'),
    ]

    operations = [
    ]
