# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-26 15:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0081_merge_20170619_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=ckeditor.fields.RichTextField(default='????????', verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.IntegerField(default=0, help_text='\u0446\u0435\u043b\u043e\u0435 \u0447\u0438\u0441\u043b\u043e \u0432 \u043c\u0438\u043d\u0443\u0442\u0430\u0445', verbose_name='\u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.IntegerField(choices=[(71, '07:00'), (72, '07:15'), (73, '07:30'), (74, '07:45'), (81, '08:00'), (82, '08:15'), (83, '08:30'), (84, '08:45'), (91, '09:00'), (92, '09:15'), (93, '09:30'), (94, '09:45'), (101, '10:00'), (102, '10:15'), (103, '10:30'), (104, '10:45'), (111, '11:00'), (112, '11:15'), (113, '11:30'), (114, '11:45'), (121, '12:00'), (122, '12:15'), (123, '12:30'), (124, '12:45'), (131, '13:00'), (132, '13:15'), (133, '13:30'), (134, '13:45'), (141, '14:00'), (142, '14:15'), (143, '14:30'), (144, '14:45'), (151, '15:00'), (152, '15:15'), (153, '15:30'), (154, '15:45'), (161, '16:00'), (162, '16:15'), (163, '16:30'), (164, '16:45'), (171, '17:00'), (172, '17:15'), (173, '17:30'), (174, '17:45'), (181, '18:00'), (182, '18:15'), (183, '18:30'), (184, '18:45'), (191, '19:00'), (192, '19:15'), (193, '19:30'), (194, '19:45'), (201, '20:00'), (202, '20:15'), (203, '20:30'), (204, '20:45'), (211, '21:00'), (212, '21:15'), (213, '21:30'), (214, '21:45'), (221, '22:00'), (222, '22:15'), (223, '22:30'), (224, '22:45')], verbose_name='\u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430'),
        ),
    ]
