# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0083_auto_20170627_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': '\u0440\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u0435', 'verbose_name_plural': '\u0440\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u044f'},
        ),
        migrations.AlterField(
            model_name='weekday',
            name='gym',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gym', verbose_name='\u0437\u0430\u043b'),
        ),
    ]
