# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-03 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_auto_20170627_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-order',), 'verbose_name': '\u0430\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u0430\u043a\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='stock',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
