# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0086_auto_20170703_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='\u0441\u043a\u0440\u044b\u0442\u044c'),
        ),
    ]
