# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0091_auto_20170711_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='policy_link',
            field=models.URLField(blank=True, help_text='\u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u0443\u043a\u0430\u0437\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u044b\u0439 URL, \u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 https://site.domain/something', null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u043e\u043b\u0438\u0442\u0438\u043a\u0443 \u043a\u043e\u043d\u0444\u0438\u0434\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([]),
        ),
    ]
