# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0092_auto_20170818_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='mainpage',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u044f\u0432\u043a\u0430 \u0441 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'),
        ),
    ]
