# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-11 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0093_formrequest_mainpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '\u0430\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u0430\u043a\u0446\u0438\u0438'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='order',
        ),
    ]
