# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0094_auto_20180111_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='\u0441\u043a\u0440\u044b\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430ffsdfsdf\u043d\u0438\u0435'),
        ),
    ]
