# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0095_auto_20180115_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gym',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
