# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-06 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0097_auto_20180306_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitneszone',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
