# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0004_auto_20170206_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Used in admin only', max_length=50, verbose_name='name')),
                ('scid', models.PositiveIntegerField(verbose_name='scid')),
                ('shop_id', models.PositiveIntegerField(verbose_name='shopid')),
                ('shop_password', models.CharField(max_length=50, verbose_name='Shop password')),
                ('order_model', models.CharField(max_length=50, verbose_name='Order model')),
                ('shop_domain', models.CharField(max_length=50, verbose_name='Shop domain')),
            ],
            options={
                'verbose_name': 'cash register',
                'verbose_name_plural': 'cash registers',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('AB', 'Alfa Click'), ('AC', 'Credit/Debit card'), ('GP', 'Cash via terminal'), ('MA', 'MasterPass'), ('MC', 'Mobile phone account'), ('PB', 'Promsvyazbank online-bank'), ('PC', 'Yandex.Money wallet'), ('SB', 'Sberbank Online'), ('WM', 'WebMoney wallet'), ('QS', 'QiWi wallet')], max_length=30)),
            ],
            options={
                'verbose_name': 'payment type',
                'verbose_name_plural': 'payment types',
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='payment_type',
            field=models.ManyToManyField(to='yandex_cash_register.PaymentType'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_cash_register.CashRegister'),
        ),
    ]
