# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 17:15
from __future__ import unicode_literals

from django.db import migrations
from yandex_cash_register import conf


def payment_types(apps, schema_editor):
    PaymentType = apps.get_model("yandex_cash_register", "PaymentType")
    for choice in conf.BASE_PAYMENT_TYPE_CHOICES:
        pay_type = PaymentType(choice=choice[0])
        pay_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0005_auto_20170427_2039'),
    ]

    operations = [
        migrations.RunPython(payment_types),
    ]
