# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import yandex_cash_register.interfaces


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('daterequest', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('phone', models.CharField(default='', max_length=20)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('club', models.CharField(default='', max_length=200)),
                ('order_type', models.CharField(default='', max_length=100)),
                ('item_kod', models.CharField(default='', max_length=100)),
            ],
            bases=(yandex_cash_register.interfaces.IPayableOrder, models.Model),
        ),
    ]
